import { GoogleGenAI, Modality } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might want to show a message to the user
  // For this exercise, we throw an error to halt execution if the key is missing.
  throw new Error("API_KEY environment variable not set. Please ensure it is configured.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export const POSTER_PROMPT = `
A high-resolution, photorealistic image of a backstage schedule poster for a rock festival.
Format: large rectangular panel (1.20m x 80cm), printed on durable matte paper, taped to a backstage wall near the dressing rooms.
Background: black with a slightly worn stage canvas texture, with simulated gaffer tape marks on the edges.
Title at the top: "The Town 2025 – Backstage Schedule – Rock Day II" in white, military stencil-style letters, with a red spray paint effect on the ends.
Left column – Skyline Stage Times:
16h30 – Creed (soundcheck at 15h45) 🎸
18h30 – Avril Lavigne (soundcheck at 17h45) 🎤
20h30 – The Killers / Arctic Monkeys (Surprise) (closed soundcheck) 🎤
22h45 – Muse (soundcheck at 21h30) 🎆
Right column – The One Stage Times:
15h00 – The Last Dinner Party
17h00 – Måneskin
19h15 – Royal Blood
21h30 – Paramore
Central area – Polaroids and notes:
A Polaroid photo of Avril Lavigne smiling in her dressing room with the handwritten caption: "Duet with Hayley – 3rd song".
A photo of Brandon Flowers adjusting his jacket, with a yellow sticky note: "Surprise entrance – keep secret until 20h29".
A photo of Matthew Bellamy testing a guitar, with a note: "Laser cue – Knights of Cydonia".
A Polaroid of Scott Stapp at soundcheck, caption: "Higher – open with it".
Production notes (in simulated cursive handwriting):
"Avoid crew crossover between Skyline and The One during stage changes."
"Confirm Avril's meet & greet at 17h00."
"Muse: check pyrotechnics sync with light operator."
Overall feel: This is the poster only festival staff see—functional but full of personality, with scribbles, colored tape, and signs of use. A visual record that, if auctioned later, would become a collector's item for fans.
`;

export const generatePosterImage = async (prompt: string): Promise<string> => {
  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image-preview',
      contents: {
        parts: [{ text: prompt }],
      },
      config: {
        responseModalities: [Modality.IMAGE, Modality.TEXT], // Must include both Modality.IMAGE and Modality.TEXT
      },
    });

    if (response.candidates && response.candidates.length > 0) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
              const base64ImageBytes: string = part.inlineData.data;
              return base64ImageBytes;
            }
        }
    }
    
    // If we reach here, no image was found in the response.
    // Let's check for a text response to provide more context for the error.
    const textResponse = response.text;
    if (textResponse) {
        console.error("API returned a text response instead of an image:", textResponse);
        throw new Error(`API returned the following text instead of an image: "${textResponse}"`);
    }

    throw new Error("No image was generated by the API.");
  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        return Promise.reject(new Error(`Failed to generate poster: ${error.message}`));
    }
    return Promise.reject(new Error("An unknown error occurred while generating the poster."));
  }
};